import React, { useState, useEffect } from 'react';
import { collection, query, orderBy, onSnapshot } from "firebase/firestore";
import { db } from '../Config/firebase';
import { PDFDownloadLink, Document, Page, Text, StyleSheet, View } from '@react-pdf/renderer';
import Task from '../Delivery/Delivery';
import AddTask from '../Delivery/AddDelivery';
import ContactUs from '../Delivery/Email';

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontSize: 12,
    },
    title: {
        fontSize: 20,
        marginBottom: 10,
        textAlign: 'center',
        fontWeight: 'bold',
        color: '#1b3d81',
    },
    section: {
        marginBottom: 10,
        padding: 10,
        border: '1px solid #ddd',
        borderRadius: 5,
        backgroundColor: '#f3f3f3',
    },
    text: {
        marginBottom: 4,
        lineHeight: 1.5,
    },
    label: {
        fontWeight: 'bold',
        color: '#b5a642',
    },
    footer: {
        textAlign: 'center',
        marginTop: 20,
        fontSize: 10,
        color: '#888',
    },
});

function DeliveryPage() {
    const [openAddModal, setOpenAddModal] = useState(false);
    const [tasks, setTasks] = useState([]);

    useEffect(() => {
        const q = query(collection(db, 'delivery'), orderBy('created', 'desc'));
        onSnapshot(q, (querySnapshot) => {
            setTasks(querySnapshot.docs.map(doc => ({
                id: doc.id,
                data: doc.data()
            })));
        });
    }, []);

    const ReportDocument = () => (
        <Document>
            <Page style={styles.page}>
                <Text style={styles.title}>Delivery Report</Text>
                {tasks.map((task) => (
                    <View style={styles.section} key={task.id}>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Delivery ID: </Text>{task.id}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Title: </Text>{task.data.title}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Description: </Text>{task.data.description}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Customer Email: </Text>{task.data.cusEmail}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Customer Phone: </Text>{task.data.cusNo}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Customer ID: </Text>{task.data.cusID}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Completed: </Text>{task.data.completed ? 'Yes' : 'No'}
                        </Text>
                    </View>
                ))}
                <Text style={styles.footer}>
                    Generated by SK Metal Shop Delivery Management System
                </Text>
            </Page>
        </Document>
    );

    return (
        <div className='w-full h-full py-[6rem] px-5 flex flex-col bg-cream'>
            <div className='text-center text-[1.5rem] font-xl font-open uppercase p-5 text-white flex justify-between w-full'>
                <header className='text-[2rem] text-black font-xl'>Delivery</header>
                <button className='btn bg-white text-black' onClick={() => setOpenAddModal(true)}>
                    Add Delivery +
                </button>
            </div>
            <div className='taskManager__container p-5'>
                <div className='flex w-full h-full flex-wrap gap-5 pb-10'>
                    {tasks.map((task) => (
                        <Task
                            id={task.id}
                            key={task.id}
                            completed={task.data.completed}
                            title={task.data.title}
                            description={task.data.description}
                            cusEmail={task.data.cusEmail}
                            cusNo={task.data.cusNo}
                            cusID={task.data.cusID}
                        />
                    ))}
                </div>
                <PDFDownloadLink
                    document={<ReportDocument />}
                    fileName="DeliveryReport.pdf"
                    className="btn bg-white hover:bg-cream text-dark-blue font-bold"
                >
                    {({ loading }) =>
                        loading ? 'Generating report...' : 'Download Delivery Report'
                    }
                </PDFDownloadLink>
            </div>
            <div className="mt-5">
                <ContactUs />
            </div>
            {openAddModal && <AddTask onClose={() => setOpenAddModal(false)} open={openAddModal} />}
            <footer className="bg-[#f5f5dc] text-white py-6 mt-40">
                <div className="container mx-auto flex flex-col md:flex-row items-center justify-between px-6">
                    <div className="flex items-center mb-4 md:mb-0">
                        <p className="font-bold text-black text-lg">SK Metal</p>
                    </div>
                    <div className="text-center md:text-left text-black mb-4 md:mb-0">
                        <p>215, Munagama Road, Horana</p>
                        <p>Email: skmetal123@gmail.com</p>
                        <p>Phone: +94 772 829 125</p>
                    </div>
                    <div className="text-center text-black md:text-right">
                        <p>&copy; {new Date().getFullYear()} SK Metal Shop. All rights reserved.</p>
                    </div>
                </div>
            </footer>
        </div>
    );
}

export default DeliveryPage;
