import Task from '../Employee/Employee';
import AddTask from '../Employee/AddEmployee';
import { useState, useEffect } from 'react';
import { collection, query, orderBy, onSnapshot } from "firebase/firestore";
import { db } from '../Config/firebase';
import { PDFDownloadLink, Document, Page, Text, StyleSheet, View } from '@react-pdf/renderer';
import { auth } from '../Config/firebase';


// Define styles for the PDF document
const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontSize: 12,
    },
    title: {
        fontSize: 20,
        marginBottom: 10,
        textAlign: 'center',
        fontWeight: 'bold',
        color: '#f3f3f3',
    },
    section: {
        marginBottom: 10,
        padding: 10,
        border: '1px solid #ddd',
        borderRadius: 5,
        backgroundColor: '#f3f3f3',
    },
    text: {
        marginBottom: 4,
        lineHeight: 1.5,
    },
    label: {
        fontWeight: 'bold',
        color: '#f3f3f3',
    },
    footer: {
        textAlign: 'center',
        marginTop: 20,
        fontSize: 10,
        color: '#888',
    },
});

function EmployeePage() {
    const [openAddModal, setOpenAddModal] = useState(false);
    const [tasks, setTasks] = useState([]);
    const [user, setUser] = useState(null);

    useEffect(() => {
        const unsubscribe = auth.onAuthStateChanged((user) => {
            setUser(user);
        });

        return () => {
            unsubscribe();
        };
    }, []);

    // Function to get all tasks from firestore in real-time
    useEffect(() => {
        const q = query(collection(db, 'employee'), orderBy('created', 'desc'));
        onSnapshot(q, (querySnapshot) => {
            setTasks(querySnapshot.docs.map(doc => ({
                id: doc.id,
                data: doc.data()
            })));
        });
    }, []);

    // Function to Generate a Report
    const ReportDocument = () => (
        <Document>
            <Page style={styles.page}>
                <Text style={styles.title}>Employees Report</Text>
                {tasks.map((task) => (
                    <View style={styles.section} key={task.id}>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Name: </Text>{task.data.ename}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Email: </Text>{task.data.email}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Address: </Text>{task.data.eaddress}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>ID: </Text>{task.data.eid}
                        </Text>
                        <Text style={styles.text}>
                            <Text style={styles.label}>Mobile: </Text>{task.data.emobile}
                        </Text>
                    </View>
                ))}
                <Text style={styles.footer}>
                    Generated by SK Metal Shop Employee Management System
                </Text>
            </Page>
        </Document>
    );

    return (
        <div className='w-full h-full py-[6rem] px-5 flex flex-col bg-light-yellow'>
            <div className='text-center text-[1.5rem] font-xl font-open uppercase p-5 text-black flex justify-between w-full'>
                <header className='text-[2rem] font-xl'>Employee</header>
                <div className='flex justify-end'>
                    <button className='btn bg-blue-600 text-white'
                        onClick={() => setOpenAddModal(true)}>
                        Add Employee +
                    </button>
                </div>
            </div>

            <div className='taskManager__container p-5 bg-cream'>
                <div className='flex w-full h-full flex-wrap gap-5 pb-10'>
                    {tasks.map((task) => (
                        <Task
                            id={task.id}
                            key={task.id}
                            ename={task.data.ename}
                            email={task.data.email}
                            eaddress={task.data.eaddress}
                            eid={task.data.eid}
                            emobile={task.data.emobile}
                        />
                    ))}
                </div>
                <PDFDownloadLink
                    document={<ReportDocument />}
                    fileName="EmployeeReport.pdf"
                    className="btn bg-blue-600 hover:bg-blue-700 text-white font-bold mt-4"
                >
                    {({ loading }) =>
                        loading ? 'Generating report...' : 'Download Employee Report'
                    }
                </PDFDownloadLink>
            </div>
            <footer className="bg-[#f5f5dc] text-white py-6 mt-40">

<div className="container mx-auto flex flex-col md:flex-row items-center justify-between px-6">
    <div className="flex items-center mb-4 md:mb-0">
        <p className="font-bold text-black text-lg">SK Metal</p>
    </div>
    <div className="text-center md:text-left text-black mb-4 md:mb-0">
        <p>215, Munagama Road, Horana</p>
        <p>Email: skmetal123@gmail.com</p>
        <p>Phone: +94 772 829 125</p>
    </div>
    <div className="text-center text-black md:text-right">
        <p>&copy; {new Date().getFullYear()} SK Metal Shop. All rights reserved.</p>
    </div>
</div>
</footer>


            {openAddModal &&
                <AddTask onClose={() => setOpenAddModal(false)} open={openAddModal} />
            }
        </div>
    );
}

export default EmployeePage;
